language: android
android:
  components:
    - build-tools-20.0.0
    - android-15
script: gradle check --stacktrace --debug
env:
  global:
  - secure: MjCN5JoPNjtXN4YInXSpT1fk5CxgmLzpgZnAye7N35Cu6U0tqztTuiCU01039dFV2T6HxKNAQnr5o//cfHU4j6HPIY0N5czL/9f3h3pX9BXMZL5/d5HDVTPpCgJTyABXHL7R1wpAJ7Z1YteXtUecwm/Vv7Hpy2zK3843pL7tsoo=
  - secure: EvS4L5bdRAle2O18+jnH/Hui8SEdk5X3jiZDHeUoVmCjBdMe6CQvU2vsKwHl6jXhiLs26MHAn5AeHjmYzC/4OtavNtvre7PslH5axnPilgSbJsueIS9uklbKB+TorFi4TV+uKGwNVcea/0emV4EJkqN7+9SMRNaqdof+k58HzxI=
